import type { Companion, Game, Venue, Booking } from "@/types";

// ─── 时间工具 ─────────────────────────────────────────────────
/** 今天指定时刻（若已过则改为明天） */
function todayAt(h: number, m = 0): string {
  const d = new Date();
  d.setHours(h, m, 0, 0);
  if (d.getTime() < Date.now()) d.setDate(d.getDate() + 1);
  return d.toISOString();
}
/** 明天指定时刻 */
function tomorrowAt(h: number, m = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
}
/** 下一个指定星期几（0=周日…6=周六）的指定时刻 */
function nextWeekdayAt(weekday: number, h: number, m = 0): string {
  const d = new Date();
  const diff = (weekday - d.getDay() + 7) % 7 || 7;
  d.setDate(d.getDate() + diff);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
}

// ─── 球伴/陪练 数据 ───────────────────────────────────────────
export const MOCK_COMPANIONS: Companion[] = [
  {
    id: "c1",
    name: "林晓雯",
    avatar: "https://picsum.photos/seed/avatar47/300/300",
    level: "高级",
    distance: "0.8km",
    rating: 4.9,
    reviewCount: 128,
    pricePerHour: 120,
    tags: ["中式八球", "教学", "耐心"],
    services: ["实战陪练", "陪练", "教学"],
    bio: "从事台球教学 6 年，擅长从零带起新手。讲解细致有耐心，走位、发球、防守全面教学，已带出多名进阶球友。",
    verified: true,
    online: true,
    ordersCompleted: 256,
    favoriteVenues: ["v1", "v2"],
    availableTime: "每天 18:00-23:00",
    gallery: [
      "https://picsum.photos/seed/cgallery1/400/300",
      "https://picsum.photos/seed/cgallery2/400/300",
      "https://picsum.photos/seed/cgallery3/400/300",
    ],
    specialties: ["中式八球走位", "发球技巧", "防守战术"],
    reviews: [
      {
        id: "r1",
        userId: "u2",
        userName: "小明",
        userAvatar: "https://picsum.photos/seed/avatar53/80/80",
        rating: 5,
        comment: "晓雯讲解非常详细，一节课就让我理解了走位！强烈推荐。",
        createdAt: "2026-05-20T14:00:00Z",
      },
      {
        id: "r2",
        userId: "u3",
        userName: "阿远",
        userAvatar: "https://picsum.photos/seed/avatar57/80/80",
        rating: 5,
        comment: "配合默契，打球很舒服，下次还来！",
        createdAt: "2026-05-18T19:00:00Z",
      },
    ],
  },
  {
    id: "c2",
    name: "张雅婷",
    avatar: "https://picsum.photos/seed/avatar39/300/300",
    level: "中级",
    distance: "1.2km",
    rating: 4.7,
    reviewCount: 89,
    pricePerHour: 90,
    tags: ["斯诺克", "实战陪练", "气氛好"],
    services: ["实战陪练", "陪练"],
    bio: "斯诺克爱好者，打了 5 年。氛围轻松不压力，喜欢和不同的朋友一起享受台球的乐趣。",
    verified: true,
    online: true,
    ordersCompleted: 134,
    favoriteVenues: ["v1", "v3"],
    availableTime: "周末全天 / 工作日 19:00-22:00",
    gallery: [
      "https://picsum.photos/seed/cgallery4/400/300",
      "https://picsum.photos/seed/cgallery5/400/300",
    ],
    specialties: ["斯诺克基础", "中远距离进球"],
    reviews: [
      {
        id: "r3",
        userId: "u4",
        userName: "晓晓",
        userAvatar: "https://picsum.photos/seed/avatar20/80/80",
        rating: 5,
        comment: "雅婷姐很 nice，打球氛围超好！",
        createdAt: "2026-05-22T20:00:00Z",
      },
    ],
  },
  {
    id: "c3",
    name: "苏思涵",
    avatar: "https://picsum.photos/seed/avatar45/300/300",
    level: "大师",
    distance: "2.1km",
    rating: 5.0,
    reviewCount: 312,
    pricePerHour: 200,
    tags: ["中式八球", "斯诺克", "职业级"],
    services: ["实战陪练", "陪练", "教学"],
    bio: "省级台球联赛女子组前三，有职业比赛经历。专注提升学员竞技水平，适合有一定基础想进阶的球友。",
    verified: true,
    online: false,
    ordersCompleted: 489,
    favoriteVenues: ["v2"],
    availableTime: "周三至周日 15:00-22:00",
    gallery: [
      "https://picsum.photos/seed/cgallery6/400/300",
      "https://picsum.photos/seed/cgallery7/400/300",
      "https://picsum.photos/seed/cgallery8/400/300",
    ],
    specialties: ["高难度走位", "斯诺克长台控制", "比赛心态调整"],
    reviews: [
      {
        id: "r4",
        userId: "u5",
        userName: "老李",
        userAvatar: "https://picsum.photos/seed/avatar60/80/80",
        rating: 5,
        comment: "思涵是真正的高手，跟她练了三节课感觉水平提升了一大截！",
        createdAt: "2026-05-15T16:00:00Z",
      },
    ],
  },
  {
    id: "c4",
    name: "陈美琪",
    avatar: "https://picsum.photos/seed/avatar44/300/300",
    level: "中级",
    distance: "1.8km",
    rating: 4.6,
    reviewCount: 67,
    pricePerHour: 80,
    tags: ["美式九球", "组局", "活跃"],
    services: ["实战陪练", "组局"],
    bio: "美式九球爱好者，喜欢组局玩赛制。每周末都在球厅，欢迎各路球友一起来切磋！",
    verified: true,
    online: true,
    ordersCompleted: 98,
    favoriteVenues: ["v3"],
    availableTime: "周末 14:00-22:00",
    gallery: ["https://picsum.photos/seed/cgallery9/400/300"],
    specialties: ["美式九球战术", "赛制组织"],
    reviews: [],
  },
  {
    id: "c5",
    name: "刘思雨",
    avatar: "https://picsum.photos/seed/avatar15/300/300",
    level: "初级",
    distance: "0.5km",
    rating: 4.5,
    reviewCount: 23,
    pricePerHour: 60,
    tags: ["中式八球", "新手友好", "价格亲民"],
    services: ["实战陪练"],
    bio: "台球新秀，打球一年多，适合同等水平的朋友一起切磋。轻松愉快，价格实惠。",
    verified: false,
    online: true,
    ordersCompleted: 31,
    favoriteVenues: ["v1"],
    availableTime: "工作日 19:00-22:00",
    gallery: ["https://picsum.photos/seed/cgallery10/400/300"],
    specialties: ["中式八球基础"],
    reviews: [],
  },
];

// ─── 球局数据 ─────────────────────────────────────────────────
export const MOCK_GAMES: Game[] = [
  {
    id: "g1",
    hostId: "c1",
    hostName: "林晓雯",
    hostAvatar: "https://picsum.photos/seed/avatar47/300/300",
    hostRating: 4.9,
    venueId: "v1",
    venueName: "红星台球会所",
    venueAddress: "天河区体育西路88号",
    gameTime: todayAt(20, 0),        // 今晚 20:00
    totalSlots: 4,
    filledSlots: 3,
    gameType: "中式八球",
    levelRequired: "中级以上",
    feeType: "AA",
    feeNote: "AA台费，约50元/人",
    note: "友谊赛，轻松为主，欢迎加入！",
    status: "recruiting",
  },
  {
    id: "g2",
    hostId: "c2",
    hostName: "张雅婷",
    hostAvatar: "https://picsum.photos/seed/avatar39/300/300",
    hostRating: 4.7,
    venueId: "v2",
    venueName: "皇冠台球城",
    venueAddress: "越秀区中山路156号",
    gameTime: tomorrowAt(19, 30),
    totalSlots: 2,
    filledSlots: 1,
    gameType: "斯诺克",
    levelRequired: "不限",
    feeType: "AA",
    feeNote: "AA台费",
    status: "recruiting",
  },
  {
    id: "g3",
    hostId: "c4",
    hostName: "陈美琪",
    hostAvatar: "https://picsum.photos/seed/avatar44/300/300",
    hostRating: 4.6,
    venueId: "v3",
    venueName: "绿台俱乐部",
    venueAddress: "海珠区工业大道66号",
    gameTime: nextWeekdayAt(6, 15, 0),
    totalSlots: 8,
    filledSlots: 5,
    gameType: "美式九球",
    levelRequired: "不限",
    feeType: "AA",
    feeNote: "AA台费+饮料，约80元/人",
    note: "周末小赛制，有奖品！",
    status: "recruiting",
  },
  {
    id: "g4",
    hostId: "c3",
    hostName: "苏思涵",
    hostAvatar: "https://picsum.photos/seed/avatar45/300/300",
    hostRating: 5.0,
    venueId: "v2",
    venueName: "皇冠台球城",
    venueAddress: "越秀区中山路156号",
    gameTime: todayAt(21, 0),
    totalSlots: 4,
    filledSlots: 4,
    gameType: "中式八球",
    levelRequired: "高级以上",
    feeType: "发起人请客",
    feeNote: "思涵请客",
    status: "full",
  },
];

// ─── 球房数据 ─────────────────────────────────────────────────
export const MOCK_VENUES: Venue[] = [
  {
    id: "v1",
    name: "红星台球会所",
    address: "天河区体育西路88号B2层",
    distance: "0.6km",
    openHours: "10:00 - 02:00",
    pricePerHour: 45,
    rating: 4.8,
    reviewCount: 320,
    images: [
      "https://picsum.photos/seed/venue1a/600/400",
      "https://picsum.photos/seed/venue1b/600/400",
      "https://picsum.photos/seed/venue1c/600/400",
    ],
    tables: [
      { id: "t1", number: "01台", type: "中式", available: true,  pricePerHour: 45 },
      { id: "t2", number: "02台", type: "中式", available: false, pricePerHour: 45 },
      { id: "t3", number: "03台", type: "斯诺克", available: true, pricePerHour: 60 },
      { id: "t4", number: "04台", type: "中式", available: true,  pricePerHour: 45 },
    ],
    residents: ["c1", "c5"],
    phone: "020-88881234",
    tags: ["环境好", "停车方便", "24小时"],
  },
  {
    id: "v2",
    name: "皇冠台球城",
    address: "越秀区中山路156号3楼",
    distance: "1.5km",
    openHours: "12:00 - 00:00",
    pricePerHour: 55,
    rating: 4.6,
    reviewCount: 218,
    images: [
      "https://picsum.photos/seed/venue2a/600/400",
      "https://picsum.photos/seed/venue2b/600/400",
    ],
    tables: [
      { id: "t5", number: "VIP-1", type: "斯诺克", available: true,  pricePerHour: 80 },
      { id: "t6", number: "VIP-2", type: "斯诺克", available: true,  pricePerHour: 80 },
      { id: "t7", number: "01台",  type: "中式",   available: false, pricePerHour: 55 },
    ],
    residents: ["c3"],
    phone: "020-33334567",
    tags: ["高端", "斯诺克专区", "空调舒适"],
  },
  {
    id: "v3",
    name: "绿台俱乐部",
    address: "海珠区工业大道66号",
    distance: "2.3km",
    openHours: "14:00 - 24:00",
    pricePerHour: 35,
    rating: 4.4,
    reviewCount: 156,
    images: [
      "https://picsum.photos/seed/venue3a/600/400",
      "https://picsum.photos/seed/venue3b/600/400",
    ],
    tables: [
      { id: "t8",  number: "01台", type: "美式", available: true, pricePerHour: 35 },
      { id: "t9",  number: "02台", type: "美式", available: true, pricePerHour: 35 },
      { id: "t10", number: "03台", type: "中式", available: true, pricePerHour: 35 },
    ],
    residents: ["c2", "c4"],
    phone: "020-55556789",
    tags: ["价格实惠", "适合组局", "年轻氛围"],
  },
];

// ─── 订单数据 ─────────────────────────────────────────────────
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "b1",
    companionId: "c1",
    companionName: "林晓雯",
    companionAvatar: "https://picsum.photos/seed/avatar47/300/300",
    service: "教学",
    duration: 2,
    venueId: "v1",
    venueName: "红星台球会所",
    bookingTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    note: "重点练习走位",
    totalPrice: 240,
    status: "已完成",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "b2",
    companionId: "c2",
    companionName: "张雅婷",
    companionAvatar: "https://picsum.photos/seed/avatar39/300/300",
    service: "实战陪练",
    duration: 1,
    venueId: "v3",
    venueName: "绿台俱乐部",
    bookingTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    totalPrice: 90,
    status: "已确认",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "b3",
    companionId: "c3",
    companionName: "苏思涵",
    companionAvatar: "https://picsum.photos/seed/avatar45/300/300",
    service: "陪练",
    duration: 3,
    venueId: "v2",
    venueName: "皇冠台球城",
    bookingTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    note: "想提升斯诺克长台控制",
    totalPrice: 600,
    status: "待确认",
    createdAt: new Date().toISOString(),
  },
];
